server {
  listen 80;
  server_name cloud.greatwebtech.cn;
  client_max_body_size 20m;

  location / {
    root /home/liuchen/pm2/little-cloud/dist;
    index index.html index.htm;
    try_files $uri $uri/ /index.html?$args;
  }
}
